### ISSUE TITLE
tnris.org: Future Considerations for Site 

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1319]
- [ ] Site Search https://github.com/TNRIS/tnris.org/issues/13
- [ ] automate accessibilty testing https://github.com/TNRIS/tnris.org/issues/112
- [ ] serve static content from a cookieless domain https://github.com/TNRIS/tnris.org/issues/114
	cookies get sent with each request so serving from a cookieless domain (e.g. static.tnris.org) will save a small amount of bandwidth per file requested by client currently a few KB per page, depending on number of images and css/js files
- [ ] SVG icons where possible https://github.com/TNRIS/tnris.org/issues/143
	Looks like vector-based icons are becoming the standard best practice in place of icon fonts and image sprites. We should probably look into using them because they have some pretty good benefits, namely they are smaller in size than images, can be styled like icon fonts, and can be made to any size.
- [ ] Need to remove typekit fonts https://github.com/TNRIS/tnris.org/issues/453
	We strongly need to consider not using fonts from typekit. The way they have to be loaded results in poor UX in a number of circumstances.

	At its best we have to add a hide/show to the whole page while the fonts load. This is why the site fades into view every time a page is visited.
	If we remove the fading, then the site loads with an unstyled font then the font jumps into place once it is loaded from typekit.
	If typekit goes down or has an interruption, our site has to wait some amount of time and then show the unstyled font after a significant delay.
	If other javascript breaks on the page it could prevent the typekit font from loading, which can result in the page never showing any content.
	We should choose a font(s) that we can either self-host or that can be loaded in a normal fashion (from Google for instance). We could either purchase the one we are currently using or use one with an amenable license to self-hosting.
- [ ] switch template engine to nunjucks https://github.com/TNRIS/tnris.org/issues/647
	swig templates library is no longer maintained (see: https://github.com/paularmstrong/swig/issues/628)
	nunjucks looks pretty solid, is actively maintained (backed by mozilla) and should be mostly compatible in terms of syntax and concepts, but I expect a few small differences exist that will make it less than a complete drop-in replacement
- [ ] repo is getting large https://github.com/TNRIS/tnris.org/issues/679
	Our git repository is getting fairly large (416M at present). Most of that is in static/images and static/documents. Github has a soft limit of 1GB, so we still have some time before it becomes a real issue. They recommend the large file storage (LFS) extension to manage larger files/repos.

	It is advertised as working well with github (files can be tracked in issues, comments, etc), but we'll need to adjust the build system slightly to accommodate. If we go over 1GB in repo size and are using LFS, we can purchase additional github space in increments of $5 per 50GB per month: https://help.github.com/articles/billing-plans-for-git-large-file-storage/

- [ ] Education & Training - Add Internships Page https://github.com/TNRIS/tnris.org/issues/730
- [ ] navbar icons messed up in IE https://github.com/TNRIS/tnris.org/issues/771
- [ ] Cleanup unused partial templates https://github.com/TNRIS/tnris.org/issues/774
- [ ] Going to empty directory path returns 403, should return 404 https://github.com/TNRIS/tnris.org/issues/829
	Hitting any empty directory returns an nginx 403 error, but it should return the custom 404 page. Ref https://github.com/TNRIS/tnris.org/issues/828
- [ ] Add twitter cards for TNRIS links https://github.com/TNRIS/tnris.org/issues/862
- [ ] Develop Marketing space on Data Download https://github.com/TNRIS/tnris.org/issues/941
- [ ] Internships Page Content Development https://github.com/TNRIS/tnris.org/issues/1199
