### ISSUE TITLE
outstanding georodeo items

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1549]
- [x]  Create sponsor graphics #1546
The GeoRodeo now has 3 sponsors:
The Texas GIS Forum
Esri
Here (graphic to follow)

Text - Thank you to our sponsors who make it possible to host the Texas GeoRodeo

- [x]  Create GeoRodeo foam core poster #1547
Thank you to the following Texas GeoRodeo sponsors:
Esri
Texas GIS Forum
Here

- [x] Repair spelling of speaker for e-blast #1548 
Martijn van Exel
Please create another graphic to be used in the e-blast to be sent next Wednesday. Correct the spelling of Martijn's van Exel's name. Currently the graphic has it spelled Martin Van Exel
Please send it to Emma at CMP - Emerlo@CMPManagement.com

**Comment by mitchellryant** [comment]
![here](https://user-images.githubusercontent.com/8459928/39431215-a88a8a16-4c55-11e8-9ec0-e6576ae96ae2.png)

**Comment by mitchellryant** [comment]
![esri](https://user-images.githubusercontent.com/8459928/39431238-b97b7768-4c55-11e8-9b2e-b01468ecdabd.png)

**Comment by christoball** [comment]
The GeoRodeo Sponsor poster board is designed just need to print out an place on foam core.

**Comment by christoball** [comment]
Sent files for final newsletter with corrected spelling

**Comment by christoball** [comment]
Sponsor board printed.
