### ISSUE TITLE
new dataset: Stratmap 2018 Crockett County

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1601]
**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer
- [x] Data Processing [renaming file, data organization]  @LaurenKirk 
- [x] Creation of derivative products @LaurenKirk 
- [x] Quality Assurance @ThorTheDestroyer

**Publication**
- [x] Move to Content Creation @ThorTheDestroyer
- [x] Coverage Map @mitchellryant
- [x] Data Publication [data catalog text\images, breakline\reports staging] @ThorTheDestroyer
- [ ] Data Story @ThorTheDestroyer @christoball https://github.com/TNRIS/tnris.org/issues/1611
- [ ] Final Publication @christoball @ThorTheDestroyer https://github.com/TNRIS/tnris.org/issues/1611
- [x] Move data to production shares @mitchellryant
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer 

**Download**
- [x] Add to Data Download  @mitchellryant https://github.com/TNRIS/data-download/issues/91

**Comment by ThorTheDestroyer** [comment]
**Data**
- [ ] Add data to measures spreadsheet @ThorTheDestroyer
- [ ] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer
- [ ] Data Processing [renaming file, data organization]  @LaurenKirk 
- [ ] Creation of derivative products @LaurenKirk 
- [ ] Quality Assurance @ThorTheDestroyer

**Publication**
- [ ] Move to Content Creation @LaurenKirk 
- [ ] Coverage Map @mitchellryant
- [ ] Data Publication [data catalog text\images, breakline\reports staging] @ThorTheDestroyer
- [ ] Data Story @ThorTheDestroyer @christoball 
- [ ] Final Publication @christoball @ThorTheDestroyer 
- [ ] Move data to production shares @mitchellryant
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer 

**Download**
- [ ] Add to Data Download  @mitchellryant

**Comment by mitchellryant** [comment]
https://tnris-twdb.carto.com/u/tnris/builder/1be7ada8-df6b-4df6-a7f4-42ed8901c704/embed
